import{i as b,S as L}from"./assets/vendor-5ObWk2rO.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&s(o)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();const S=document.querySelector(".container"),i=document.querySelector(".form"),a=document.querySelector(".gallery");i.addEventListener("submit",$);function $(r){r.preventDefault(),O(),a.innerHTML="";const n=r.target.elements.query.value,t=`https://pixabay.com/api/?key=42059071-0978dc0d7158b742eee7c30f5&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safeserch=true`;fetch(t).then(o=>{if(!o.ok)throw new Error(o.statusText);return o.json()}).then(o=>{if(o.hits.length===0||n==="")b.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"center"});else{const u=o.hits.map(({webformatURL:f,largeImageURL:m,tags:d,likes:p,views:h,comments:y,downloads:g})=>`<a href=${f} class='link'
      ><li class='item'>
        <img class='image' src=${m} alt=${d} />
        <p><b>Likes:</b>${p}</p>
        <p><b>Views:</b>${h}</p>
        <p><b>Comments:</b>${y}</p>
        <p><b>Downloads:</b>${g}</p></li
    ></a>`).join("");a.insertAdjacentHTML("beforeend",u),l.refresh(),i.reset()}}).catch(o=>{console.log(o)}).finally(()=>{q(),i.reset()})}const E={captions:!0,captionSelector:"img",captionsData:"alt",captionPosition:"bottom",animation:250},l=new L(".gallery a",E);l.on("show.simplelightbox");function O(){const r=document.createElement("span");r.classList.add("loader"),S.append(r)}function q(){const r=document.querySelector(".loader");r&&r.remove()}
//# sourceMappingURL=index.js.map
